#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    rightPot,       sensorPotentiometer)
#pragma config(Sensor, in2,    leftPot,        sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           LB,            tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           LF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RB,            tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           RF,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           ALB,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ALT,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ART,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           ARB,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           IL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          IR,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
float targetValue;
int rightArmTarget;
int leftArmTarget;
bool isRun = True;

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	targetValue=4000;
  rightArmTarget = 0;
  leftArmTarget = 0;
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................
	//startTask(driveBase);
	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////


void drive()
{
	//int right_armVal;
	//int left_armVal;
	int armLoop = 0;
  motor[RF]=vexRT[Ch2];
  motor[RB]=-vexRT[Ch2];
  motor[LB]=motor[LF]=vexRT[Ch3];

  //Arm control
  if (vexRT[Btn6D]== 1)
	{
		motor[ALB]=motor[ALT]=127;
		motor[ARB]=motor[ART]=-127;
	}
	else if (vexRT[Btn6U] == 1)
	{
		motor[ALB]=motor[ALT]=-127;
		motor[ARB]=motor[ART]=127;
		armLoop = 0;
	}
	else
	{
		motor[ALB]=motor[ALT]=-10;
		motor[ARB]=motor[ART]=10;
		//rightArmTarget = SensorValue[leftPot];
		//leftArmTarget = SensorValue[rightPot];
		//startTask(armPID);
		}

	//Intake control
	if (vexRT[Btn5U]== 1)
	{
		motor[IR]=127;
		motor[IL]=127;
	}
	else if (vexRT[Btn5D] == 1)
	{
		motor[IR]=-127;
		motor[IL]=-127;
	}
	else
	{
		motor[IR]=0;
		motor[IL]=0;
	}
	/*right_armVal = SensorValue[leftPot];
	left_armVal = SensorValue[rightPot];
	armPID(right_armVal,left_armVal);*/
}


task usercontrol()
{
	// User control code here, inside the loop
	//targetValue = 10000;
	//startTask(driveBase);
	//startTask(arm);
	//startTask(drive);
	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................
//		motor[port1]=motor[port2]=vexRT[Ch1];
//		motor[port3]=motor[port4]=vexRT[Ch3];
	//targetValue=4000;
	//startTask(driveBase);
	
		
	//rightArmTarget = SensorValue[rightPot];
  //leftArmTarget = SensorValue[leftPot];

  //rightArmTarget = 25;
  //leftArmTarget = 25;
  //startTask(armPID);
	drive();

	  UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	}
}
